### PR TITLE
support inclusion by Polymer.mixinBehaviors

### LINKED ISSUE #30: Using Polymer 2.0 class based element definition doesn't register validator element
### Description

When using the Polymer 2.0 class based element definition for defining a validator element the validator isn't registered properly as the ```is``` property is ```undefined``` due to the property being declared as a static class property which isn't defined at ```this```, which at the time of reference refers to an instance rather than the class definition.

### Example

https://gist.github.com/juriejan/b6bcb4cbf816d84fb2aeea0a0fc0dd1d

### PR DESCRIPTION
**Pull request by TomK**
Closes #30 (Issue)
Closes #34 (PR)

### CODE REVIEW

**Comment by TomK** [comment]
@notwaldorf PR as discussed on slack yesterday :)

**Comment by nickpelone** [comment]
any chance of this getting merged and a point release cut anytime in the near future?

**Comment by nickpelone** [comment]
thank you!!

**Comment by notwaldorf** [comment]
(sorry it fell off my radar; thanks for the reminder!)

**Pull request merged**
