### PR TITLE
singleton

### PR DESCRIPTION
**Pull request by garlicnation**

### CODE REVIEW

**Comment by notwaldorf** [comment]
@garlicnation all these tests are angry :(

**Comment by notwaldorf** [comment]
@garlicnation ping! what's the status of this PR?

**Comment by garlicnation** [comment]
I'll clean this up when I'm in the office tomorrow.

**Comment by MeTaNoV** [comment]
this might solve an issue I have where I defined a custom validator with a property/attribute, and this property is not updated so that when I access to it in the `validate()` function, `this.property` is the default value... whereas, in the `attached()`, I have the value I specified in the element attribute as expected!

```javascript
<dom-module id="gold-password-input-validator">
  <script>
    Polymer({
      is: 'gold-password-input-validator',
      behaviors: [
        Polymer.IronValidatorBehavior
      ],
      properties: {
        pattern: {
          type: String,
          value: '.*',
        }
      },
      attached: function() {
        console.log("gold-password-input-validator pattern: " + this.pattern);        
      },
      validate: function(value) {
        var regexp = new RegExp("^" + this.pattern + "$");
        console.log("gold-password-input-validator pattern: " + this.pattern);
        var result = !value || (value.match(regexp) !== null);
        console.log("result: " + result);
        return result;
      }
    });
  </script>
</dom-module>
```

**Comment by notwaldorf** [comment]
Going to close this PR since it's pretty old, and the tests are super angry. @garlicnation please re-open when it's ready to be looked at again.

**Pull request closed without merging**
